### ISSUE TITLE
CR-Unblocker Changelog on Chrome startup

### ISSUE THREAD

**Issue by zeromido** [Onestay/CR-Unblocker#29] opened 2017-08-18 14:09 UTC
Sometimes when I start Chrome [CR-Unblocker Changelog](https://cr-unblocker.com/) opens like the first time I installed CR-Unblocker.

**Comment by Onestay** [comment] 2017-08-18 14:21
Yeah I've noticed that as well. I've had that with other extensions that do
something on install or on update as well. So I think it is an issue with
chrome itself and not our extension. I'll look into it tho.

**Comment by zeromido** [comment] 2017-08-18 22:13
Good luck! I'll send feedback to Chrome about that.

**Comment by irgendwie** [comment] 2017-09-10 17:15
Caused by https://github.com/Onestay/CR-Unblocker/blob/master/src/background_script.js#L225

"Fired when the extension is first installed, when the extension is updated to a new version, and **when Chrome is updated to a new version**." https://developer.chrome.com/apps/runtime#event-onInstalled

**Comment by zeromido** [comment] 2017-09-10 18:05
My Chrome just got updated to v61 and CR-Unblocker Changelog opened again after a while.
I hope there's a way to make the changelog open only once.

**Comment by Onestay** [comment] 2017-09-29 13:29
Fixed in 92713e5fef77b05c4f1780c0351a9caa13cbb269

**Closed by Onestay** 2017-09-29 13:29 UTC
